# Generated by Django 3.0.3 on 2020-02-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, default='username', max_length=100)),
                ('password', models.CharField(blank=True, default='password', max_length=100)),
                ('is_parent', models.BooleanField(default=False)),
                ('profile_image', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('family_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='project_4.FamilyMember')),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_url', models.TextField(blank=True, default='')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='project_4.Family')),
                ('person_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_member', to='project_4.FamilyMember')),
            ],
        ),
    ]
